from __future__ import print_function, unicode_literals
"""Add LocaleCache

Revision ID: 27fb5b742a71
Revises: 1340df738748
Create Date: 2015-06-02 16:59:21.964043

"""

# revision identifiers, used by Alembic.
revision = '27fb5b742a71'
down_revision = '1340df738748'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LocationCache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.Unicode(length=64), nullable=False),
    sa.Column('lookup_time', sa.DateTime(), nullable=False),
    sa.Column('hostname', sa.Unicode(length=255), nullable=True),
    sa.Column('city', sa.Unicode(length=255), nullable=True),
    sa.Column('country', sa.Unicode(length=255), nullable=True),
    sa.Column('most_specific_subdivision', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
    op.create_index('ix_LocationCache_city', 'LocationCache', ['city'])
    op.create_index('ix_LocationCache_hostname', 'LocationCache', ['hostname'])
    op.create_index('ix_LocationCache_most_specific_subdivision', 'LocationCache', ['most_specific_subdivision'])
    op.create_index('ix_LocationCache_country', 'LocationCache', ['country'])


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LocationCache')
    ### end Alembic commands ###
