"""Added Invitations and AcceptedInvitations table

Revision ID: 2b4052e3d5aa
Revises: 20cb28a89cc6
Create Date: 2016-06-24 12:54:58.303783

"""

# revision identifiers, used by Alembic.
revision = '2b4052e3d5aa'
down_revision = '20cb28a89cc6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
