from __future__ import print_function, unicode_literals
"""Add config on relations between federated schedulers and experiments

Revision ID: 35756029a48a
Revises: 4b8e6be32ada
Create Date: 2013-12-30 14:39:42.765444

"""

# revision identifiers, used by Alembic.
revision = '35756029a48a'
down_revision = '4b8e6be32ada'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SchedulerExternalExperimentEntry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('scheduler_id', sa.Integer(), nullable=False),
    sa.Column('config', sa.String(length=1024)),
    sa.ForeignKeyConstraint(['experiment_id'], ['Experiment.id'], ),
    sa.ForeignKeyConstraint(['scheduler_id'], ['Scheduler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id','scheduler_id'),
    mysql_engine='InnoDB'
    )
    op.drop_table(u'ExperimentExternalScheduler')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'ExperimentExternalScheduler',
    sa.Column(u'experiment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column(u'scheduler_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], [u'Experiment.id'], name=u'ExperimentExternalScheduler_ibfk_1'),
    sa.ForeignKeyConstraint(['scheduler_id'], [u'Scheduler.id'], name=u'ExperimentExternalScheduler_ibfk_2'),
    sa.PrimaryKeyConstraint(u'experiment_id', u'scheduler_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('SchedulerExternalExperimentEntry')
    ### end Alembic commands ###
