"""Add invitation related tables

Revision ID: 42bd0c8938f9
Revises: 54e63b0a9b06
Create Date: 2016-09-01 17:48:05.935684

"""

# revision identifiers, used by Alembic.
revision = '42bd0c8938f9'
down_revision = '54e63b0a9b06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'Invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.Unicode(length=32), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('expire_date', sa.DateTime(), nullable=True),
    sa.Column('max_number', sa.Integer(), nullable=True),
    sa.Column('allow_register', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], [u'Group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id'),
    mysql_engine=u'InnoDB'
    )
    op.create_index(u'ix_Invitation_unique_id', u'Invitation', ['unique_id'], unique=False)
    op.create_table(u'AcceptedInvitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('accepted_date', sa.DateTime(), nullable=False),
    sa.Column('registered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], [u'Invitation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitation_id', 'user_id'),
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'AcceptedInvitation')
    op.drop_index(u'ix_Invitation_unique_id', table_name=u'Invitation')
    op.drop_table(u'Invitation')
    ### end Alembic commands ###
