from __future__ import print_function, unicode_literals
"""Add Scheduler info to the database

Revision ID: 4b8e6be32ada
Revises: 54e60d31349a
Create Date: 2013-12-27 19:54:24.832911

"""

# revision identifiers, used by Alembic.
revision = '4b8e6be32ada'
down_revision = '54e60d31349a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Scheduler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('scheduler_type', sa.String(length=255), nullable=False),
    sa.Column('config', sa.String(length=4096), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_engine='InnoDB'
    )
    op.create_table('SchedulerResource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scheduler_id', sa.Integer(), nullable=False),
    sa.Column('slots', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scheduler_id'], ['Scheduler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name','scheduler_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('ExperimentInstance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('min_slot', sa.Integer(), nullable=False),
    sa.Column('max_slot', sa.Integer(), nullable=False),
    sa.Column('scheduler_resource_id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['Experiment.id'], ),
    sa.ForeignKeyConstraint(['scheduler_resource_id'], ['SchedulerResource.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name','scheduler_resource_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('ExperimentExternalScheduler',
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('scheduler_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['Experiment.id'], ),
    sa.ForeignKeyConstraint(['scheduler_id'], ['Scheduler.id'], ),
    sa.PrimaryKeyConstraint('experiment_id', 'scheduler_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ExperimentExternalScheduler')
    op.drop_table('ExperimentInstance')
    op.drop_table('SchedulerResource')
    op.drop_table('Scheduler')
    ### end Alembic commands ###
