from __future__ import print_function, unicode_literals
"""Add client and client parameter

Revision ID: 54e60d31349a
Revises: 4c23f9943036
Create Date: 2013-12-23 22:18:59.616842

"""

# revision identifiers, used by Alembic.
revision = '54e60d31349a'
down_revision = '4c23f9943036'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ExperimentClientParameter',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('experiment_id', sa.Integer(), nullable=False),
        sa.Column('parameter_name', sa.String(length=255), nullable=False),
        sa.Column('parameter_type', sa.String(length=15), nullable=False),
        sa.Column('value', sa.String(length=600), nullable=False),
        sa.ForeignKeyConstraint(['experiment_id'], ['Experiment.id'], ),
        sa.PrimaryKeyConstraint('id'),
        mysql_engine='InnoDB'
    )
    op.add_column(u'Experiment', sa.Column('client', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'Experiment', 'client')
    op.drop_table('ExperimentClientParameter')
    ### end Alembic commands ###
