"""Very minor changes to the Invitations

Revision ID: 54e63b0a9b06
Revises: 2b4052e3d5aa
Create Date: 2016-06-29 14:54:41.267178

"""

# revision identifiers, used by Alembic.
revision = '54e63b0a9b06'
down_revision = '2b4052e3d5aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
