"""Add longer ip address called pack

Revision ID: 585d74c833a6
Revises: 42bd0c8938f9
Create Date: 2016-11-23 17:43:03.266314

"""

# revision identifiers, used by Alembic.
revision = '585d74c833a6'
down_revision = '42bd0c8938f9'

from alembic import op
import sqlalchemy as sa
import sqlalchemy.sql as sql

metadata = sa.MetaData()
loc = sa.Table('LocationCache', metadata,
    sa.Column('id', sa.Integer()),
)

def upgrade():
    op.execute(loc.delete())
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'LocationCache', sa.Column('pack', sa.Unicode(length=255), nullable=False))
    op.create_index(u'ix_LocationCache_pack', u'LocationCache', ['pack'], unique=False)
    op.drop_index(u'ix_LocationCache_ip', table_name=u'LocationCache')
    op.drop_column(u'LocationCache', u'ip')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'LocationCache', sa.Column(u'ip', sa.Unicode(length=255), nullable=False))
    op.create_index(u'ix_LocationCache_ip', u'LocationCache', [u'ip'], unique=False)
    op.drop_index(u'ix_LocationCache_pack', table_name=u'LocationCache')
    op.drop_column(u'LocationCache', 'pack')
    ### end Alembic commands ###
