PATHS = [ 
    ('$', 'redirect:/weblab/client'),
    ('/$', 'redirect:/weblab/client'),
    ('/weblab/$', 'redirect:/weblab/client'),
    ('/weblab/client$', 'redirect:/weblab/client/index.html'),
    ('/weblab/client/weblabclientlab/configuration.js', 'file:/home/lrg/weblab/weblabdeusto/tools/wcloud/wcloud/test/testinstance_sqlite/client/configuration.js'),
    ('/weblab/client/weblabclientadmin/configuration.js', 'file:/home/lrg/weblab/weblabdeusto/tools/wcloud/wcloud/test/testinstance_sqlite/client/configuration.js'),
    ('/weblab/client/weblabclientlab//img/client/images/', 'file:/home/lrg/weblab/weblabdeusto/tools/wcloud/wcloud/test/testinstance_sqlite/client/images/'),
    ('/weblab/client/weblabclientadmin//img/client/images/', 'file:/home/lrg/weblab/weblabdeusto/tools/wcloud/wcloud/test/testinstance_sqlite/client/images/'),
    ('/weblab/client', 'file:/home/lrg/Envs/wcloud/local/lib/python2.7/site-packages/weblabdeusto-5.0-py2.7.egg/weblabdeusto_data/war'),
    ('/weblab/soap/', 'proxy-sessions:weblabsessionid:route1=http://localhost:10004/weblab/soap,'),
    ('/weblab/json/', 'proxy-sessions:weblabsessionid:route1=http://localhost:10006/weblab/json,'),
    ('/weblab/xmlrpc/', 'proxy-sessions:weblabsessionid:route1=http://localhost:10005/weblab/xmlrpc,'),
    ('/weblab/web/', 'proxy-sessions:weblabsessionid:route1=http://localhost:10007/weblab/web/,'),
    ('/weblab/administration', 'proxy-sessions:weblabsessionid:route1=http://localhost:10008/weblab/administration,'),
    ('/weblab/login/soap/', 'proxy-sessions:loginweblabsessionid:route1=http://localhost:10000/weblab/login/soap,'),
    ('/weblab/login/json/', 'proxy-sessions:loginweblabsessionid:route1=http://localhost:10002/weblab/login/json,'),
    ('/weblab/login/xmlrpc/', 'proxy-sessions:loginweblabsessionid:route1=http://localhost:10001/weblab/login/xmlrpc,'),
    ('/weblab/login/web/', 'proxy-sessions:loginweblabsessionid:route1=http://localhost:10003/weblab/login/web,'),
    ('/weblab/', 'file:/home/lrg/Envs/wcloud/local/lib/python2.7/site-packages/weblabdeusto-5.0-py2.7.egg/webserver'),
    ('', 'redirect:/weblab/client/index.html'),
]
