.. note::

    At this moment, we are migrating the documentation from the
    `old documentation site <http://code.google.com/p/weblabdeusto/wiki/Latest_Index>`_, so most
    documentation is still there.

.. contents:: Table of Contents

General
-------

.. toctree::
   :maxdepth: 1

   summary
   federation
   screenshots
   technical
   publications

Users
-----

This section is intended for people who is going to install the WebLab-Deusto
system and connect existing laboratories. 

.. toctree::
   :maxdepth: 2

   installation
   first_steps
   installation_next_steps
   authentication
   tools


Remote laboratory development
-----------------------------

This section is intended for people who is going to create a new laboratory
using the WebLab-Deusto tools.

**TO BE WRITTEN**


External systems
----------------

This section is intended for people who is going to integrate WebLab-Deusto in
external systems, such as Learning Management Systems, Content Management
Systems, OAuth providers or similar.

.. toctree::
   :maxdepth: 2

   federation_for_external_tools
   other_approaches
   lms4labs

WebLab-Deusto Development
-------------------------

.. toctree::
   :maxdepth: 2

   development

Appendixes
----------

.. toctree::

   download_from_github
