"""Add db_name

Revision ID: 2d16d7104dd6
Revises: 41daf2bf458b
Create Date: 2015-02-09 15:25:22.452554

"""

# revision identifiers, used by Alembic.
revision = '2d16d7104dd6'
down_revision = '41daf2bf458b'

from alembic import op
import sqlalchemy as sa
import sqlalchemy.sql as sql

metadata = sa.MetaData()
entities_table = sa.Table('entities', metadata,
    sa.Column('id', sa.Integer),
    sa.Column('name', sa.Unicode(length=200)),
    sa.Column('db_name', sa.Unicode(length=200)),
)

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('db_name', sa.Unicode(length=200), nullable=True))
    ### end Alembic commands ###
    sentence = sql.select([entities_table.c.id])
    connection = op.get_bind()
    rows = connection.execute(sentence)
    for row in rows:
        current_id = row[entities_table.c.id]
        db_name = u'wcloud%s' % current_id
        print("Entity %s: db_name=%s" % (current_id, db_name))
        update_stmt = entities_table.update().where(entities_table.c.id == current_id).values(db_name = db_name)
        connection.execute(update_stmt)

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'db_name')
    ### end Alembic commands ###
