"""Add first structure

Revision ID: 41daf2bf458b
Revises: 552742dd018b
Create Date: 2015-02-09 15:24:54.607237

"""

# revision identifiers, used by Alembic.
revision = '41daf2bf458b'
down_revision = '552742dd018b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('logo', sa.LargeBinary(length=16777216), nullable=False),
    sa.Column('logo_ext', sa.Unicode(length=4), nullable=False),
    sa.Column('base_url', sa.Unicode(length=200), nullable=False),
    sa.Column('link_url', sa.Unicode(length=300), nullable=False),
    sa.Column('google_analytics_number', sa.Unicode(length=30), nullable=True),
    sa.Column('start_port_number', sa.Integer(), nullable=True),
    sa.Column('end_port_number', sa.Integer(), nullable=True),
    sa.Column('deployed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Unicode(length=200), nullable=False),
    sa.Column('password', sa.Unicode(length=200), nullable=False),
    sa.Column('full_name', sa.Unicode(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tokens')
    op.drop_table('entities')
    ### end Alembic commands ###
